# Generated by Django 6.0.5 on 2026-05-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaMaster',
            fields=[
                ('criteria_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('LIST', 'List')], max_length=20)),
                ('allowed_operator', models.CharField(max_length=20)),
                ('allowed_values', models.JSONField(blank=True, help_text='Applicable only for LIST type criteria', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'criteria_master',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipMaster',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('scholarship_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, help_text='Terms, conditions, eligibility criteria, award rules, and any other scholarship details.', null=True)),
                ('no_of_scholarships', models.CharField(blank=True, help_text='Number of scholarships/awards available.', max_length=200, null=True)),
                ('scholarship_amount', models.CharField(blank=True, help_text='Amount and payment details as specified in the scholarship document.', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scholarship Master',
                'verbose_name_plural': 'Scholarship Master',
                'db_table': 'scholarship_master',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20)),
                ('criteria_value', models.TextField(help_text='Selected value(s) for this scholarship criterion')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sch_master.criteriamaster')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='sch_master.scholarshipmaster')),
            ],
            options={
                'db_table': 'scholarship_criteria',
            },
        ),
    ]
