# Generated by Django 6.0.5 on 2026-06-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScholarshipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('institute_email', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('single_parent_child', models.BooleanField(default=False)),
                ('jee_advance_rank', models.IntegerField(blank=True, null=True)),
                ('jee_crl_rank', models.IntegerField(blank=True, null=True)),
                ('jee_category_rank', models.IntegerField(blank=True, null=True)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_passbook_file', models.FileField(upload_to='documents/passbook/')),
                ('jee_certificate_file', models.FileField(upload_to='documents/jee/')),
                ('category_certificate_file', models.FileField(blank=True, null=True, upload_to='documents/category/')),
                ('income_proof_file', models.FileField(upload_to='documents/income/')),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_scholarship_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled')], default='APPLIED', max_length=30)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('award_year', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch_master.scholarshipmaster')),
            ],
            options={
                'db_table': 'student_scholarship',
            },
        ),
        migrations.CreateModel(
            name='StudentScholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('award_year', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch_master.scholarshipmaster')),
            ],
            options={
                'db_table': 'student_scholarships',
            },
        ),
    ]
