# Generated by Django 6.0.5 on 2026-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0002_studentscholarshipprofile_studentscholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='domicile_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/domicile/'),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='endorsement_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/endorsement/'),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='fee_receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/fee/'),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='no_disciplinary_action',
            field=models.BooleanField(default=False),
        ),
    ]
