# Generated by Django 6.0.5 on 2026-07-26 02:19

from django.db import migrations


def remove_endorsement_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = DATABASE() "
            "AND table_name = 'student_scholarship_profile' "
            "AND column_name = 'endorsement_certificate_file'"
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE student_scholarship_profile DROP COLUMN endorsement_certificate_file")


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0003_studentscholarshipprofile_domicile_certificate_file_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_endorsement_column, migrations.RunPython.noop),
    ]
