# Generated by Django 6.0.5 on 2026-07-26 02:52

from django.db import migrations


def remove_student_scholarships_table(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = 'student_scholarships'"
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute("DROP TABLE student_scholarships")


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0004_remove_studentscholarshipprofile_endorsement_certificate_file_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(remove_student_scholarships_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='studentscholarshipprofile',
                    name='jee_advance_rank',
                ),
                migrations.DeleteModel(
                    name='StudentScholarships',
                ),
            ],
        ),
    ]
