# Generated by Django 6.0.5 on 2026-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0005_remove_studentscholarshipprofile_jee_advance_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscholarshipprofile',
            name='fee_receipt_file',
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='fee_receipt_even_semester_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/fee/even/'),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='fee_receipt_odd_semester_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/fee/odd/'),
        ),
    ]
