# Generated by Django 6.0.5 on 2026-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0006_remove_studentscholarshipprofile_fee_receipt_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='class_12_marksheet_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/class_12/'),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='class_12_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
