# Generated by Django 6.0.5 on 2026-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0009_add_student_scholarship_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='current_semester',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='programme',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
