# Generated by Django 6.0.5 on 2026-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0010_studentscholarshipprofile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscholarshipprofile',
            name='current_semester',
        ),
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='current_batch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
