# Generated by Django 6.0.5 on 2026-08-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0011_remove_studentscholarshipprofile_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='admission_batch',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
