# Generated by Django 6.0.5 on 2026-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0012_studentscholarshipprofile_admission_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscholarshipprofile',
            name='current_semester',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
