# Generated by Django 6.0.5 on 2026-08-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch_master', '0014_ensure_socialapp_sites_table'),
    ]

    operations = [
    ]
